name: tenantmodule
description: A new Flutter project.

publish_to: 'none'

version: 2.0.0+2      #Version name + version code

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  animated_splash_screen: ^1.3.0
  camera: ^0.10.3+2
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  http: ^0.13.5
  image_picker: ^0.8.7+1
  intl: ^0.17.0
  intl_phone_field: ^3.1.0
  mpesa_flutter_plugin: ^1.6.1
  open_file: ^3.2.1
  path_provider: ^2.0.14
  pattern_formatter: ^2.0.0
  pdf: ^3.9.0
  provider: ^6.0.5
  radio_button_form_field: ^0.0.4
  shared_preferences: ^2.0.20
  url_launcher: ^6.1.10

  # cupertino_icons: ^1.0.2
  # animated_splash_screen: ^1..0
  # font_awesome_flutter: ^10.1.0
  # pattern_formatter: ^2.0.0
  # radio_button_form_field: ^0.0.4
  # intl: ^0.17.0
  # provider: ^6.0.3
  # http: ^0.13.4
  # shared_preferences: ^2.0.15
  # url_launcher: ^6.1.5
  # mpesa_flutter_plugin: ^1.6.0
  # intl_phone_field: ^3.1.0
  # pdf: ^3.8.3
  # open_file: ^3.2.1
  # path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

